/* CATALOGO:
   nome: idioma-en
   categoria: UTIL
   objetivo: O dicionário português -> inglês do site da ālea (áudios 6928/6932 do Cassiano, 06/10/2026). Carregado pelo
      js/idioma.js só quando a pessoa escolhe EN. GERADO por 03_site/_idioma_en_2026-10-06/montar_dicionario_v1.py a partir de
      chaves_vN.json + traducoes_vN.py — não edite aqui: edite a tradução lá e gere de novo.
   status: ativo (gerado)
*/

window.ALEA_EN = {
"<a class=\"botao contorno\" href=\"index.html\">Voltar ao site</a>": "<a class=\"botao contorno\" href=\"index.html\">Back to the site</a>",
"<a href=\"index.html\">Ver as peças</a>": "<a href=\"index.html\">See the pieces</a>",
"<em>Alea</em>, em latim, significa dado. Representa o acaso, o jogo, a sorte, a aleatoriedade que minha cabeça estava naquele momento, aquilo que é lançado e já não pode simplesmente voltar.": "<em>Alea</em> is Latin for “die” — as in dice. It stands for chance, the game, luck, the randomness my head was in at that moment: something that’s been thrown and can’t just come back.",
"<small class=\"em-breve\">Em breve</small>": "<small class=\"em-breve\">Coming soon</small>",
"<small>Em breve</small>": "<small>Coming soon</small>",
"<small>Sob consulta</small>": "<small>Price on request</small>",
"<span data-campo=\"responsavel\">Cassiano Rosado</span>, <span data-campo=\"cidade\">Jataí</span>/<span data-campo=\"uf\">GO</span> · CNPJ <span data-campo=\"cnpj\">61.338.171/0001-10</span> · identidade visual por <a href=\"https://www.instagram.com/mirellagaetti/\" target=\"_blank\" rel=\"noopener\">Mirella Gaetti</a> · <a href=\"a-alea.html\">Quem somos nós</a> · <a href=\"trocas-e-entrega.html\">Trocas, devoluções e entregas</a> · <a href=\"privacidade.html\">Política de privacidade</a>": "<span data-campo=\"responsavel\">Cassiano Rosado</span>, <span data-campo=\"cidade\">Jataí</span>/<span data-campo=\"uf\">GO</span> · CNPJ <span data-campo=\"cnpj\">61.338.171/0001-10</span> · visual identity by <a href=\"https://www.instagram.com/mirellagaetti/\" target=\"_blank\" rel=\"noopener\">Mirella Gaetti</a> · <a href=\"a-alea.html\">About us</a> · <a href=\"trocas-e-entrega.html\">Returns, exchanges &amp; shipping</a> · <a href=\"privacidade.html\">Privacy policy</a>",
"<strong style=\"font-weight:600\">Mensagem para Presente</strong><br><span class=\"loja-miudo\">Adicione uma mensagem personalizada que será impressa e enviada com seu presente.</span>": "<strong style=\"font-weight:600\">Gift Message</strong><br><span class=\"loja-miudo\">Add a personal message — we’ll print it and send it along with your gift.</span>",
"<strong>\"Baixar meus dados\"</strong> — um arquivo com tudo que a ālea &amp; Co. tem sobre você, inclusive a memória da visita;": "<strong>\"Download my data\"</strong> — a file with everything ālea &amp; Co. has on you, including your visit history;",
"<strong>\"Excluir minha conta\"</strong> — encerra o acesso na hora; a ālea &amp; Co. conclui a exclusão em até 10 dias e mantém só o que a lei fiscal exige (o pedido, sem o nome do pet).": "<strong>\"Delete my account\"</strong> — cuts off access right away; ālea &amp; Co. finishes the deletion within 10 days and keeps only what tax law requires (the order, without your pet’s name).",
"<strong>Como desligar:</strong> desmarque \"Lembrar as peças que eu vi\" na sua ficha, ou apague os dados do site no seu navegador. O que já foi lembrado sai junto se você pedir a exclusão da conta.": "<strong>How to turn it off:</strong> uncheck \"Remember the pieces I viewed\" in your profile, or clear this site’s data in your browser. Whatever was already remembered goes too if you ask for your account to be deleted.",
"<strong>Ficha e conta:</strong> enquanto a conta existir. Conta sem nenhum acesso e sem pedido por 24 meses é apagada.": "<strong>Profile and account:</strong> for as long as the account exists. Accounts with no logins and no orders for 24 months are deleted.",
"<strong>Google</strong>: o login, e os anúncios nos limites da seção acima. As fontes das letras também vêm do Google Fonts, que recebe o endereço de IP de quem visita.": "<strong>Google</strong>: sign-in, and ads within the limits of the section above. The site’s fonts also come from Google Fonts, which receives the visitor’s IP address.",
"<strong>Hetzner Online</strong> (empresa de servidores, na <strong>Alemanha</strong>): é onde o site e o banco de dados ficam guardados, num país da União Europeia, sob a lei europeia de proteção de dados.": "<strong>Hetzner Online</strong> (a hosting company in <strong>Germany</strong>): that’s where the site and the database live, in a European Union country, under European data protection law.",
"<strong>Isso vale aqui, com uma ressalva que você declara na hora da compra.</strong> Antes de pôr a peça na sacola, você marca uma declaração dizendo que revisou o nome, a grafia e as cores, e que está ciente das condições abaixo. É o mesmo texto que aparece na página de cada produto:": "<strong>That applies here, with one exception you agree to at checkout.</strong> Before a piece goes into your bag, you tick a statement saying you’ve checked the name, the spelling and the colors, and that you’re aware of the conditions below. It’s the same text that shows up on every product page:",
"<strong>Jataí-GO:</strong> entrega combinada diretamente com você.": "<strong>Jataí-GO:</strong> delivery arranged directly with you.",
"<strong>Memória da visita:</strong> até 12 meses depois da última visita.": "<strong>Visit history:</strong> up to 12 months after your last visit.",
"<strong>O que NÃO é lembrado:</strong> o nome do pet que você digita na personalização, a posição do mouse na tela, gravação da tela, nada fora do site da ālea &amp; Co.": "<strong>What is NOT remembered:</strong> the pet name you type when customizing, your mouse position on screen, screen recordings, anything outside the ālea &amp; Co. site.",
"<strong>O que é lembrado:</strong>": "<strong>What is remembered:</strong>",
"<strong>Outras cidades:</strong> envio por transportadora ou Correios. O valor do frete é calculado e informado <em>antes</em> do pagamento, nunca depois.": "<strong>Other cities:</strong> shipped by carrier or Correios (Brazilian mail). The shipping cost is calculated and shown <em>before</em> you pay, never after.",
"<strong>Pedidos:</strong> pelo prazo das obrigações fiscais e de garantia do vendedor.": "<strong>Orders:</strong> for as long as the seller’s tax and warranty obligations require.",
"<strong>Por quanto tempo:</strong> até 12 meses depois da sua última visita.": "<strong>For how long:</strong> up to 12 months after your last visit.",
"<strong>Pra que serve:</strong> te mostrar de novo, quando você voltar, as peças que mais te interessaram (\"Continue de onde parou\"), e entender quais peças e quais anúncios funcionam — em número.": "<strong>What it’s for:</strong> showing you again, when you come back, the pieces you were most into (\"Pick up where you left off\"), and understanding which pieces and which ads work — in numbers.",
"<strong>Só acontece se você tocar em \"Pode\"</strong> no aviso que aparece uma vez, ou marcar \"Lembrar as peças que eu vi\" na sua ficha. Sem isso, nada da sua navegação sai do seu aparelho.": "<strong>It only happens if you tap \"Sure\"</strong> on the notice that pops up once, or tick \"Remember the pieces I viewed\" in your profile. Without that, nothing about your browsing leaves your device.",
"<strong>Transportadora</strong>: o endereço e o nome, pra entregar.": "<strong>Carrier</strong>: your address and name, to deliver.",
"<strong>ViaCEP</strong>: só o <strong>CEP</strong> que você digita, pra preencher o endereço sozinho (a consulta sai do nosso servidor, não do seu aparelho).": "<strong>ViaCEP</strong>: only the <strong>ZIP code (CEP)</strong> you type, to fill in your address automatically (the lookup goes out from our server, not from your device).",
"<strong>ZELES</strong> (a empresa que opera o site e o servidor da ālea &amp; Co.): guarda e processa os dados <strong>por instrução da ālea &amp; Co.</strong> — é a <em>operadora</em>; a ālea &amp; Co. é a <em>controladora</em> (LGPD, art. 39).": "<strong>ZELES</strong> (the company that runs the site and server for ālea &amp; Co.): stores and processes the data <strong>on ālea &amp; Co.’s instructions</strong> — it’s the <em>processor</em>; ālea &amp; Co. is the <em>controller</em> (LGPD, art. 39).",
"<strong>de onde você chegou</strong>: o anúncio, a campanha e o termo que você pesquisou no Google, quando o anúncio informa isso — e só o <strong>nome do site</strong> que te trouxe, nunca o endereço completo.": "<strong>where you came from</strong>: the ad, the campaign and the term you searched on Google, when the ad passes that along — and only the <strong>name of the site</strong> that brought you, never the full address.",
"A Ayla não é uma cachorra, é uma artista! Tem milhares de seguidores no Instagram (<a href=\"https://www.instagram.com/aylapompom/\" target=\"_blank\" rel=\"noopener\">@aylapompom</a>) e, acima de tudo, é muito fotogênica. Pra ela, tinha que ser algo jamais visto, surpreendente e muito chamativo.": "Ayla isn’t a dog, she’s an artist! She’s got thousands of followers on Instagram (<a href=\"https://www.instagram.com/aylapompom/\" target=\"_blank\" rel=\"noopener\">@aylapompom</a>) and, above all, she’s super photogenic. For her, it had to be something never seen before — surprising and totally eye-catching.",
"A peça é feita <strong>sob encomenda</strong>: ela entra na fila de impressão depois da <strong>confirmação do pagamento</strong>, e fica pronta em <strong>3 dias úteis</strong> a partir daí. O prazo de entrega é contado além desse e depende da forma de envio.": "Each piece is <strong>made to order</strong>: it goes into the print queue after <strong>payment is confirmed</strong> and is ready <strong>3 business days</strong> later. Delivery time is on top of that and depends on the shipping method.",
"A ālea &amp; Co. <strong>não vende, não aluga e não repassa</strong> seus dados. Eles passam só por quem é necessário:": "ālea &amp; Co. <strong>doesn’t sell, rent or share</strong> your data. It only goes to whoever is strictly needed:",
"Ao entrar você concorda com a <a href=\"privacidade.html\">Política de Privacidade</a> da ālea &amp; Co.": "By signing in you agree to ālea &amp; Co.’s <a href=\"privacidade.html\">Privacy Policy</a>.",
"As peças da ālea &amp; Co. são <strong>feitas sob encomenda e personalizadas</strong> com o nome do seu cão. Isso muda algumas regras em relação a um produto de prateleira, e está tudo escrito aqui <em>antes</em> da compra — como manda o artigo 30 do Código de Defesa do Consumidor.": "ālea &amp; Co. pieces are <strong>made to order and personalized</strong> with your dog’s name. That changes a few rules compared with an off-the-shelf product, and it’s all written here <em>before</em> you buy — as article 30 of Brazil’s Consumer Protection Code (CDC) requires.",
"CUSTOM<small>em breve</small>": "CUSTOM<small>coming soon</small>",
"DAILY<small>em breve</small>": "DAILY<small>coming soon</small>",
"FAN<small>em breve</small>": "FAN<small>coming soon</small>",
"GLOW<small>em breve</small>": "GLOW<small>coming soon</small>",
"MEET<small>em breve</small>": "MEET<small>coming soon</small>",
"Minha capivara é construída em <em>low poly</em>, uma técnica que representa formas utilizando poucas faces geométricas, normalmente compostas por polígonos e triângulos.": "My capybara is built in <em>low poly</em>, a technique that shows shapes using just a few geometric faces — usually polygons and triangles.",
"Na prática: pediu e mudou de ideia <strong>antes</strong> de a impressão começar, é só escrever para o SAC, <a href=\"mailto:sac@alea3d.co\">sac@alea3d.co</a> — cancelamos e devolvemos. Depois que a peça com o nome do seu pet já está sendo impressa, ela não serve para mais ninguém, e é aí que a ressalva vale. <strong>Defeito, vício ou erro de fabricação continuam cobertos sempre</strong>, sem prazo de 7 dias nenhum: é a seção abaixo.": "In practice: ordered and changed your mind <strong>before</strong> printing started? Just email our customer service, <a href=\"mailto:sac@alea3d.co\">sac@alea3d.co</a> — we cancel and refund. Once the piece with your pet’s name is already printing, it’s no good to anyone else, and that’s where the exception kicks in. <strong>Defects, flaws or manufacturing errors are always covered</strong>, no 7-day limit at all: see the section below.",
"No dia seguinte, procurando um nome para aquilo que ainda nem sabia exatamente no que se transformaria, encontrei a história de <em>alea iacta est</em> — a célebre expressão associada a Júlio César e à travessia do Rubicão.": "The next day, looking for a name for something I didn’t even know what it would become yet, I came across the story of <em>alea iacta est</em> — the famous phrase linked to Julius Caesar crossing the Rubicon.",
"Nome escrito errado <strong>por você</strong> na hora do pedido. Você revisa e confirma o nome antes de finalizar — confira com calma.": "A name misspelled <strong>by you</strong> when ordering. You review and confirm the name before checking out — take your time.",
"Não tem uma conta? <span class=\"loja-link sublinha\">Cadastre-se</span>": "Don’t have an account? <span class=\"loja-link sublinha\">Sign up</span>",
"O que você preencher na área <strong>Conta</strong>: nome, WhatsApp, data de aniversário (opcional), endereços de entrega e seus pets (nome, espécie, porte, raça). Serve para <strong>produzir e entregar a sua peça</strong> e <strong>falar com você sobre o pedido</strong>. Você corrige ou tira qualquer item na própria área Conta.": "Whatever you fill in under <strong>Account</strong>: name, WhatsApp, birthday (optional), delivery addresses and your pets (name, species, size, breed). It’s used to <strong>make and deliver your piece</strong> and to <strong>talk to you about your order</strong>. You can fix or remove anything right there in Account.",
"O único cookie do site é o da <strong>sessão de quem entrou com o Google</strong> (descrito acima). Quem não entra não recebe cookie nenhum. A sacola continua guardada dentro do seu próprio navegador, neste aparelho. Se e quando uma campanha do Google Ads for ligada, os cookies de medição do Google passam a existir, e esta política é atualizada antes.": "The site’s only cookie is the <strong>session cookie for people who signed in with Google</strong> (described above). If you don’t sign in, you get no cookie at all. Your bag is kept inside your own browser, on this device. If and when a Google Ads campaign is switched on, Google’s measurement cookies will come into play, and this policy will be updated first.",
"PLAY<small>em breve</small>": "PLAY<small>coming soon</small>",
"Pela LGPD você pode ver, corrigir, levar, apagar seus dados e retirar um consentimento, a qualquer momento, sem custo. <strong>Na área Conta, sem pedir a ninguém:</strong>": "Under the LGPD (Brazil’s data protection law) you can see, correct, take, delete your data and withdraw consent, anytime, free of charge. <strong>Right in Account, without asking anyone:</strong>",
"Pelo artigo 49 do Código de Defesa do Consumidor, quem compra fora de um estabelecimento físico — pela internet, por WhatsApp, por telefone — pode desistir em até <strong>7 dias corridos</strong> contados do recebimento do produto, devolvendo-o e recebendo de volta tudo que pagou, frete incluído.": "Under article 49 of Brazil’s Consumer Protection Code, anyone buying outside a physical store — online, via WhatsApp, by phone — can back out within <strong>7 calendar days</strong> of receiving the product, returning it and getting back everything they paid, shipping included.",
"Por fora da conta: somente pelo SAC, no e-mail <a href=\"mailto:sac@alea3d.co\">sac@alea3d.co</a>. <!-- 27/09/2026 (áudio 2356 do Cassiano): tudo pelo SAC, sem WhatsApp nem Instagram; e-mail pessoal dele só em \"Quem é o responsável\". Antes: _versoes_anteriores/privacidade_so_sac_antes_2026-09-27/ -->": "Outside your account: only through customer service, at <a href=\"mailto:sac@alea3d.co\">sac@alea3d.co</a>. <!-- 27/09/2026 (áudio 2356 do Cassiano): tudo pelo SAC, sem WhatsApp nem Instagram; e-mail pessoal dele só em \"Quem é o responsável\". Antes: _versoes_anteriores/privacidade_so_sac_antes_2026-09-27/ -->",
"Posso lembrar as peças que você viu, pra te mostrar de novo quando voltar? <a href=\"privacidade.html#memoria\">Como funciona</a>": "Can I remember the pieces you checked out, so I can show them to you again when you’re back? <a href=\"privacidade.html#memoria\">How it works</a>",
"Pra manter você conectada(o), o site guarda um <strong>cookie de sessão</strong> (um código aleatório, sem dado seu dentro). Ele vale por 60 dias ou até você tocar em \"Sair\".": "To keep you signed in, the site stores a <strong>session cookie</strong> (a random code, with none of your data in it). It lasts 60 days or until you tap \"Sign out\".",
"Quando você chega por um anúncio e faz um pedido, a ālea &amp; Co. informa ao Google <strong>que aquele clique virou pedido e o valor</strong> (pelo código do clique do anúncio, sem nome, sem e-mail). É o que ensina o anúncio a encontrar pessoas parecidas com quem compra.": "When you arrive through an ad and place an order, ālea &amp; Co. tells Google <strong>that the click turned into an order, and its value</strong> (using the ad’s click code, no name, no email). That’s what teaches the ad to find people similar to the ones who buy.",
"Quando você toca em \"Continuar com o Google\", o Google nos entrega <strong>seu nome, seu e-mail e sua foto</strong> — e nada mais. A ālea &amp; Co. <strong>não recebe e não guarda senha nenhuma</strong>: quem confere que é você é o Google. Você pode desligar o acesso da ālea &amp; Co. a qualquer momento em <a href=\"https://myaccount.google.com/connections\" target=\"_blank\" rel=\"noopener\">myaccount.google.com/connections</a>.": "When you tap \"Continue with Google\", Google gives us <strong>your name, your email and your photo</strong> — nothing else. ālea &amp; Co. <strong>doesn’t receive or store any password</strong>: Google is the one checking it’s you. You can revoke ālea &amp; Co.’s access anytime at <a href=\"https://myaccount.google.com/connections\" target=\"_blank\" rel=\"noopener\">myaccount.google.com/connections</a>.",
"SENSE<small>em breve</small>": "SENSE<small>coming soon</small>",
"Se a peça chegar quebrada, com falha de impressão, com o nome errado ou diferente do que você pediu, o prazo para reclamar é de <strong>90 dias</strong> (art. 26 do CDC, produto durável). Mande uma foto para o SAC, <a href=\"mailto:sac@alea3d.co\">sac@alea3d.co</a>: eu reimprimo e reenvio <strong>sem custo nenhum</strong> para você — ou devolvo o valor, se preferir.": "If your piece arrives broken, with a print flaw, with the wrong name or different from what you ordered, you have <strong>90 days</strong> to let us know (art. 26 of the CDC, durable goods). Send a photo to customer service, <a href=\"mailto:sac@alea3d.co\">sac@alea3d.co</a>: I’ll reprint and resend it <strong>at no cost at all</strong> to you — or refund you, if you prefer.",
"Se você marcou <strong>\"Quero receber novidades e ofertas da ālea &amp; Co.\"</strong>, seu e-mail e seu WhatsApp podem ser enviados ao Google <strong>embaralhados (criptografia SHA-256)</strong> pra que os anúncios da ālea &amp; Co. alcancem você — ou, ao contrário, <strong>deixem de aparecer</strong> pra quem já é cliente. Sem essa marcação, isso não acontece.": "If you ticked <strong>\"I want news and offers from ālea &amp; Co.\"</strong>, your email and WhatsApp may be sent to Google <strong>scrambled (SHA-256 encryption)</strong> so ālea &amp; Co.’s ads can reach you — or, the other way around, <strong>stop showing</strong> to people who are already customers. Without that box ticked, this doesn’t happen.",
"Somente pelo SAC da ālea &amp; Co., por e-mail: <a href=\"mailto:sac@alea3d.co\">sac@alea3d.co</a>. Respondo em horário comercial.": "Only through ālea &amp; Co.’s customer service, by email: <a href=\"mailto:sac@alea3d.co\">sac@alea3d.co</a>. I reply during business hours.",
"São pequenas formas que, observadas separadamente, podem parecer desconectadas ou até (ālea)tórias, entenderam o trocadilho né!?<br><span style=\"white-space:nowrap\">😂😂😂😂😂</span><br>Mas, quando se encontram, constroem algo completo.": "They’re little shapes that, looked at one by one, might seem disconnected or even (ālea)tory — get the pun?!<br><span style=\"white-space:nowrap\">😂😂😂😂😂</span><br>But when they come together, they build something whole.",
"Você pode comprar na ālea &amp; Co. <strong>sem criar conta</strong>: a sacola continua funcionando e o pedido continua fechando pelo WhatsApp. Se você <strong>entrar com o Google</strong>, a ālea &amp; Co. passa a guardar a sua ficha (nome, e-mail, WhatsApp, endereço e seus pets) e os seus pedidos, pra você não digitar tudo de novo em nenhum aparelho. E, <strong>só se você disser \"pode\"</strong>, o site lembra quais peças você olhou, pra te mostrar de novo quando voltar.": "You can shop at ālea &amp; Co. <strong>without creating an account</strong>: the bag still works and the order still closes over WhatsApp. If you <strong>sign in with Google</strong>, ālea &amp; Co. keeps your profile (name, email, WhatsApp, address and your pets) and your orders, so you don’t have to type it all again on any device. And <strong>only if you say \"sure\"</strong>, the site remembers which pieces you looked at, to show them to you again when you come back.",
"quais fotos você arrastou pra ver, quais páginas de produto abriu, se personalizou (<strong>não o que você escreveu</strong>), o que foi pra sacola e se o pedido foi fechado;": "which photos you swiped through, which product pages you opened, whether you customized (<strong>not what you typed</strong>), what went into the bag and whether the order was placed;",
"quais peças ficaram na sua tela e <strong>por quanto tempo</strong> (somado, não segundo a segundo);": "which pieces stayed on your screen and <strong>for how long</strong> (added up, not second by second);",
"*Ps.: Acompanha tigela em inox.": "*P.S.: Comes with a stainless steel bowl.",
", CNPJ": ", CNPJ",
". CNPJ": ". CNPJ",
". Contato:": ". Contact:",
"2026 — Todos os direitos reservados.": "2026 — All rights reserved.",
"@alea.co_": "@alea.co_",
"@eaibora.3d": "@eaibora.3d",
"A Cláudia foi a nossa modelo na divulgação da coleção Pet Bowl Wave. Muito fotogênica, foi quem mais fez a equipe rir na hora das fotos, com seu jeito brincalhão e medroso.": "Cláudia was our model for the Pet Bowl Wave launch. Super photogenic, she was the one who made the crew laugh the most during the shoot, with her playful, scaredy-cat way.",
"A aleatoriedade.": "The randomness.",
"A base elevada deixa o cão comer com o pescoço em posição mais natural, sem ter que abaixar a cabeça até o chão.": "The raised base lets your dog eat with its neck in a more natural position, without having to bend its head all the way to the floor.",
"A capivara da ālea, desenhada em low poly": "The ālea capybara, drawn in low poly",
"A capivara.": "The capybara.",
"A coleção Stria Planter nasce da combinação entre textura e simplicidade. Suas ranhuras verticais acompanham toda a peça, criando movimento e valorizando a luz e as sombras ao longo da superfície.": "The Stria Planter collection comes from mixing texture and simplicity. Its vertical grooves run along the whole piece, creating movement and playing up light and shadow across the surface.",
"A família Lamel nasce da sobreposição visual de lâminas verticais que percorrem toda a peça, criando profundidade, movimento e diferentes percepções conforme o ângulo de observação.": "The Lamel family comes from vertical blades layered visually along the whole piece, creating depth, movement and a different look depending on the angle you see it from.",
"A ideia deste comedouro veio da vontade de criar algo com muita personalidade, um presente pro meu cachorro. Pra quem não sabe, eu tenho dois Goldens, e o meu primeiro se chama Luke, que é o lindão/gordão aí da capa! Haha’": "The idea for this bowl came from wanting to make something with a ton of personality — a gift for my dog. For those who don’t know, I have two Goldens, and my first one is Luke, the handsome chunky boy on the cover! Haha",
"A onda que dá nome à peça vem do grafismo da marca — é o mesmo desenho que aparece na embalagem e na tag, aplicado na curva do comedouro.": "The wave the piece is named after comes from the brand’s graphic pattern — the same design you’ll find on the packaging and the tag, applied to the curve of the bowl.",
"A sorte.": "The luck.",
"A sua ficha": "Your profile",
"A ālea & Co. faz comedouros e acessórios pet personalizados, impressos em 3D sob encomenda em Jataí, Goiás.": "ālea & Co. makes personalized pet bowls and accessories, 3D printed to order in Jataí, Goiás (Brazil).",
"A ālea que também pode ser ligada ao aleatório, nasceu de um acaso. Mas ficou por escolha.": "ālea, which can also be linked to “aleatory” (random), was born by chance. But it stayed by choice.",
"Acaso que vira forma.": "Chance turned into form.",
"Adicionar à Lista de Desejos": "Add to Wishlist",
"Adicionar à sacola": "Add to bag",
"Adicione sua senha": "Enter your password",
"Afinal, a impressora estava comprada! Haha’ A decisão estava tomada. E, no fundo, eu sabia que não queria voltar.": "I mean, the printer was already bought! Haha The decision was made. And deep down, I knew I didn’t want to go back.",
"Agora não": "Not now",
"Ainda não temos peça com “zzzz”. Fala com a gente: fazemos sob encomenda.": "We don’t have a piece with “zzzz” yet. Hit us up: we make things to order.",
"Amarelo": "Yellow",
"Amarelo Girassol": "Sunflower Yellow",
"Anúncios do Google": "Google Ads",
"Ao finalizar a compra": "At checkout",
"Areia": "Sand",
"Arraste a tela para baixo para pesquisar produtos": "Pull the screen down to search for products",
"Arraste para girar": "Drag to rotate",
"As fotos de cães que aparecem no site são de peças reais já entregues, publicadas com autorização dos donos. Se você é dono de um dos cães fotografados e quer a foto fora do ar, é só pedir — sai no mesmo dia, sem discussão.": "The dog photos you see on the site are real pieces already delivered, posted with the owners’ permission. If you own one of the dogs in the photos and want the picture taken down, just ask — it comes down the same day, no questions asked.",
"As peças da ālea & Co. que você guardou no coração.": "The ālea & Co. pieces you saved to your heart.",
"Aumentar": "Increase",
"Ayla Pompom": "Ayla Pompom",
"Azul": "Blue",
"Azul Aqua": "Aqua Blue",
"Azul Bebê": "Baby Blue",
"Azul Céu": "Sky Blue",
"Azul Marinho": "Navy Blue",
"Bicolor": "Two-tone",
"Bordô": "Burgundy",
"Branco": "White",
"Buscamos representar as cores com a maior fidelidade possível. Ainda assim, pequenas variações de tonalidade podem ocorrer entre a visualização na tela e o produto real, devido às diferentes configurações de brilho, contraste e cor de cada dispositivo.": "We do our best to show colors as accurately as possible. Still, small differences in tone can happen between what you see on screen and the real product, because every device has its own brightness, contrast and color settings.",
"Buscar": "Search",
"Buscar item": "Search items",
"Buscar produtos": "Search products",
"Cachorro": "Dog",
"Caixa com a tag da marca — serve de presente": "Box with the brand tag — perfect as a gift",
"Cancelar": "Cancel",
"Caramelo": "Caramel",
"Carregando a peça…": "Loading the piece…",
"Categorias": "Categories",
"Cinza": "Gray",
"Clique novamente para tela cheia.": "Click again for full screen.",
"Clique numa foto pra ampliar.": "Click a photo to zoom in.",
"Clássico": "Classic",
"Cláudia": "Cláudia",
"Com formas orgânicas e uma superfície marcada por ondas suaves, nossa saboneteira traz movimento e personalidade para um objeto presente todos os dias.": "With organic shapes and a surface marked by soft waves, our soap dish brings movement and personality to something you use every single day.",
"Com formas suaves e linhas que percorrem toda a peça, este vaso foi pensado para trazer textura e movimento à decoração de forma leve e elegante.": "With soft shapes and lines that run along the whole piece, this vase was designed to bring texture and movement to your decor in a light, elegant way.",
"Com quem os dados são compartilhados": "Who the data is shared with",
"Comedouro": "Bowl",
"Comedouro e porta-saquinho na mesma estampa, com o mesmo nome.": "Bowl and poop bag holder in the same pattern, with the same name.",
"Comedouro elevado com o nome do seu cão impresso no corpo da peça.": "Raised bowl with your dog’s name printed right into the piece.",
"Comedouro elevado e porta-saquinho impressos em 3D com o nome do seu cão. Feitos sob encomenda em Jataí-GO.": "Raised bowl and poop bag holder, 3D printed with your dog’s name. Made to order in Jataí, Goiás (Brazil).",
"Comedouro · PET": "Bowl · PET",
"Como pedir troca, devolução ou reembolso": "How to request an exchange, return or refund",
"Compacto e leve, pode ser preso à guia, mochila ou bolsa pela alça superior, ficando sempre à mão quando você precisar.": "Compact and light, it clips onto the leash, backpack or bag by the top strap, so it’s always right there when you need it.",
"Comprar agora": "Buy now",
"Contém": "Includes",
"Cookies": "Cookies",
"Cor da base": "Base color",
"Cor do nome": "Name color",
"Cor do topo": "Top color",
"Cor principal": "Main color",
"Cores da peça": "Piece colors",
"Criado para levar os saquinhos higiênicos de forma prática e discreta, este porta-saquinhos combina funcionalidade com um desenho low poly e cheio de personalidade.": "Made to carry poop bags in a practical, low-key way, this poop bag holder combines function with a low poly design full of personality.",
"Criado para levar os saquinhos higiênicos de forma prática e discreta, este porta-saquinhos combina funcionalidade com um desenho low poly e cheio de personalidade. Seu corpo facetado traz a estética geométrica característica da ālea & Co., enquanto a abertura lateral permite retirar os saquinhos com facilidade durante o passeio.": "Made to carry poop bags in a practical, low-key way, this poop bag holder combines function with a low poly design full of personality. Its faceted body has the geometric look that’s signature ālea & Co., while the side opening makes it easy to pull bags out on your walk.",
"Curiosamente, antes mesmo de existir o nome ālea, uma coisa já estava decidida: minha marca teria uma capivara.": "Funny thing: even before the name ālea existed, one thing was already decided — my brand would have a capybara.",
"Cáqui": "Khaki",
"Declaro que revisei cuidadosamente todas as informações da personalização, incluindo nome, grafia e cores. Declaro, ainda, estar ciente e de acordo com as condições acima aplicáveis a produtos personalizados, inclusive quanto a cancelamentos e devoluções.": "I confirm that I have carefully reviewed all the personalization details, including name, spelling and colors. I also confirm that I am aware of and agree to the conditions above that apply to personalized products, including those regarding cancellations and returns.",
"Declaro que revisei cuidadosamente todas as informações da personalização. Declaro, ainda, estar ciente e de acordo com as condições acima aplicáveis a produtos personalizados, inclusive quanto a cancelamentos e devoluções.": "I confirm that I have carefully reviewed all the personalization details. I also confirm that I am aware of and agree to the conditions above that apply to personalized products, including those regarding cancellations and returns.",
"Depois de criar o meu primeiro comedouro, bateu aquele sentimento de justiça de pai: tudo que se dá pra um filho, tem que dar pro outro! Haha’": "After making my first bowl, that dad sense of fairness kicked in: whatever you give one kid, you’ve got to give the other! Haha",
"Desejos": "Wishlist",
"Diferença pequena de tom de cor entre a foto do site e a peça física. Filamento tem variação de lote, e tela de celular não mostra cor igual à do olho.": "A slight difference in color tone between the site photo and the actual piece. Filament varies from batch to batch, and a phone screen doesn’t show color the way your eye does.",
"Digite aqui.": "Type here.",
"Dimensões": "Dimensions",
"Diminuir": "Decrease",
"Direito de arrependimento (compra fora da loja física)": "Right of withdrawal (purchases outside a physical store)",
"Disponível em diferentes formatos e cores, foi criado para se adaptar a diversos ambientes sem perder sua identidade.": "Available in different shapes and colors, it was designed to fit all kinds of spaces without losing its identity.",
"Dourado": "Gold",
"Dourado com Glitter": "Glitter Gold",
"Dá para fazer em low poly!? 😜": "Can it be done in low poly!? 😜",
"E a vontade de trazer ideias para o mundo real!": "And the urge to bring ideas into the real world!",
"E acredito que Deus teve muito a ver com isso, colocando um novo caminho diante de mim justamente quando eu mais precisava encontrá-lo.": "And I believe God had a lot to do with it, putting a new path in front of me right when I needed to find one the most.",
"E como ela é muito comilona, na hora de criar lembrei da Magali, da Turma da Mônica, que também é associada à melancia, a fruta preferida dela. Pra mim, melancia tem uma combinação de cores linda, que sempre funciona em objeto, textura e desenho. Tinha tudo a ver com ela.": "And since she’s a total foodie, when I was designing it I thought of Magali, from Monica’s Gang (a classic Brazilian comic), who’s also linked to watermelon, her favorite fruit. To me, watermelon has a gorgeous color combo that always works — in objects, textures and drawings. It was so her.",
"E por que uma capivara?": "And why a capybara?",
"E talvez não pudesse existir representação melhor para a ālea & Co.": "And maybe there couldn’t be a better symbol for ālea & Co.",
"E vocês devem ter reparado no anjinho da foto de capa, né? Esse anjinho é a Cláudia.": "And you must have noticed the little angel in the cover photo, right? That little angel is Cláudia.",
"E, pra não ficar igual mesmo, ele ganhou textura: na impressão, o bico faz pequenos movimentos aleatórios nas paredes, e a peça sai com um toque áspero, diferente do liso.": "And so it wouldn’t be the same at all, it got texture: while printing, the nozzle makes tiny random moves on the walls, and the piece comes out with a rough feel instead of smooth.",
"E-mail": "Email",
"Ela representa muito do lugar de onde vim.": "She stands for a lot of where I come from.",
"Elevado": "Raised",
"Elevado por pequenos pés, o vaso ganha leveza visual e presença, transformando plantas e flores em parte da composição do espaço.": "Raised on little feet, the vase gains visual lightness and presence, turning plants and flowers into part of the room’s composition.",
"Elevated Pet Bowl": "Elevated Pet Bowl",
"Em um dos momentos mais difíceis da minha vida, sofrendo por quem não devia, quando eu ainda não sabia exatamente para que lado seguir, encontrei, por acaso, em uma madrugada um vídeo sobre impressão 3D. Não estava procurando por aquilo. Mas alguma coisa ali me chamou imediatamente a atenção: a possibilidade de criar, inventar e transformar uma ideia em algo que, até então, simplesmente não existia.": "In one of the hardest moments of my life, hurting over someone I shouldn’t have, still not knowing which way to go, I stumbled on a video about 3D printing in the middle of the night. I wasn’t looking for it. But something there grabbed my attention right away: the chance to create, invent and turn an idea into something that, until then, simply didn’t exist.",
"Embalagem": "Packaging",
"Encomendar agora": "Order now",
"Entrar": "Sign in",
"Entrar com e-mail e senha": "Sign in with email and password",
"Entrar com o Google": "Sign in with Google",
"Entre na sua conta da ālea & Co.: dados pessoais, endereços, pedidos e lista de desejos.": "Sign in to your ālea & Co. account: personal info, addresses, orders and wishlist.",
"Entrega": "Shipping",
"Então fique à vontade para usar e abusar da sua criatividade pra também deixar ela do jeitinho que seu pet merece!": "So feel free to go wild with your creativity and make it exactly the way your pet deserves!",
"Ephix Vase": "Ephix Vase",
"Escolha a cor": "Choose the color",
"Escolha o acabamento acima": "Choose the finish above",
"Escolher Produtos": "Choose Products",
"Escolher mais Produtos": "Choose more Products",
"Esqueci minha senha": "Forgot my password",
"Essa linguagem acabou se tornando parte da minha identidade e do jeito como crio as coisas. Antes de desenvolver uma peça, quase sempre me pergunto:": "That style ended up becoming part of my identity and the way I make things. Before designing a piece, I almost always ask myself:",
"Estou ciente da possível variação de cor.": "I’m aware the color may vary.",
"Eu queria uma peça bonita, leve, colorida e, CLARO, em low poly.": "I wanted a piece that was pretty, light, colorful and, OF COURSE, low poly.",
"Ex.: exemplo@mail.com": "E.g.: example@mail.com",
"Exterior": "Exterior",
"Fechar": "Close",
"Fechar a foto": "Close the photo",
"Fechar aviso": "Close notice",
"Fechar o álbum": "Close the album",
"Finalizar Compra": "Checkout",
"Foi aí que surgiu a ideia de um comedouro elevado: o pote fica mais perto da altura do peito dele, e ele come sem precisar abaixar tanto o pescoço.": "That’s when the idea of a raised bowl came up: the bowl sits closer to chest height, so he eats without having to bend his neck so much.",
"Foi nele também que experimentei, pela primeira vez, o filamento em tom de mármore. Ele não é áspero como o texturizado, mas lembra muito um mármore de verdade. Chama muita atenção e é muito bonito, como dá pra ver nas fotos dos álbuns.": "It was also the first time I tried marble-look filament. It isn’t rough like the textured one, but it really looks like real marble. It turns heads and it’s gorgeous, as you can see in the album photos.",
"Formato": "Shape",
"Fosco": "Matte",
"Foto ampliada": "Enlarged photo",
"Foto anterior": "Previous photo",
"Fotos de clientes": "Customer photos",
"Gato": "Cat",
"Home · HOME": "Home · HOME",
"Ideal para flores secas, pequenos arranjos ou até mesmo para ser usado sozinho, como objeto decorativo.": "Perfect for dried flowers, small arrangements or even on its own, as a decorative object.",
"Infelizmente, um dia depois das fotos, ela foi atropelada e não resistiu. Por isso resolvi fazer essa collab com o nome dela, pra que a Cláudia siga com a gente em cada peça.": "Sadly, the day after the shoot, she was hit by a car and didn’t make it. That’s why I decided to do this collab with her name, so Cláudia stays with us in every piece.",
"Instagram da ālea & Co. (@alea.co_)": "ālea & Co. on Instagram (@alea.co_)",
"Instagram do canal eai, bora? (@eaibora.3d)": "Instagram for the eai, bora? channel (@eaibora.3d)",
"Interior": "Interior",
"Kit ālea": "ālea Kit",
"Lamel": "Lamel",
"Laptop Stand": "Laptop Stand",
"Laranja": "Orange",
"Lembrar a sua visita": "Remember your visit",
"Lembrar sua visita": "Remember your visit",
"Lilás": "Lilac",
"Linktree": "Linktree",
"Lista de Desejos": "Wishlist",
"Longum": "Longum",
"Luke": "Luke",
"Mais do que acomodar uma planta, Stria Planter foi pensado para fazer parte da decoração.": "More than just holding a plant, the Stria Planter was designed to be part of the decor.",
"Make": "Make",
"Makeup Layer Organizer": "Makeup Layer Organizer",
"Cella": "Cella",
"A Cella foi criada para reunir, separar e acomodar pequenos objetos de forma prática, sem abrir mão do design. Seus diferentes compartimentos criam espaços pensados para cada necessidade, enquanto a gaveta amplia as possibilidades de organização e mantém aquilo que você prefere guardar mais reservado.": "Cella was created to gather, separate and hold small objects in a practical way, without giving up on design. Its different compartments create spaces made for each need, while the drawer widens the ways to organize and keeps what you prefer to store more private.",
"As linhas verticais que percorrem toda a peça acrescentam textura e ritmo ao desenho, transformando um objeto funcional em parte da composição do ambiente.": "The vertical lines running along the whole piece add texture and rhythm to the design, turning a functional object into part of the room’s composition.",
"Strata": "Strata",
"A Strata nasce da ideia de construir a organização aos poucos, permitindo que diferentes módulos se encontrem, se sobreponham e formem uma composição única.": "Strata comes from the idea of building organization little by little, letting different modules meet, stack and form a unique composition.",
"Seu desenho arredondado contrasta com a sequência delicada de linhas que envolve toda a peça, criando textura, movimento e uma presença marcante mesmo nas formas mais simples.": "Its rounded design contrasts with the delicate sequence of lines wrapping the whole piece, creating texture, movement and a striking presence even in the simplest shapes.",
"Modular e versátil, a Strata pode acompanhar diferentes usos e espaços, crescendo de acordo com aquilo que você precisa organizar. Cada camada acrescenta uma nova possibilidade, sem perder a unidade do conjunto.": "Modular and versatile, Strata can follow different uses and spaces, growing with whatever you need to organize. Each layer adds a new possibility, without losing the unity of the set.",
"Mais do que guardar, a Strata transforma a organização em composição.": "More than storing, Strata turns organization into composition.",
"Marcas de uso. A peça é de uso diário de um animal.": "Signs of use. The piece is used every day by an animal.",
"Marque a declaração acima para adicionar à sacola.": "Tick the statement above to add it to your bag.",
"Marrom": "Brown",
"Mas havia ainda outra parte dessa história.": "But there was still another part to this story.",
"Mas você pode personalizar do seu jeito, com três cores, com duas ou com uma só. Nele dá pra brincar com a imaginação!": "But you can customize it your way, with three colors, two or just one. This one really lets your imagination run wild!",
"Material": "Material",
"Matteo": "Matteo",
"Melancia": "Watermelon",
"Mesmo com uma composição marcante, suas linhas mantêm a peça elegante e fácil de combinar. Sozinho, funciona como um objeto decorativo; com folhagens, flores secas ou arranjos naturais, ganha ainda mais personalidade.": "Even with a bold composition, its lines keep the piece elegant and easy to match. On its own, it works as a decorative object; with foliage, dried flowers or natural arrangements, it gets even more personality.",
"Meu comedouro principal, por exemplo, nasceu assim, inteiramente construído em low poly. Nem todo projeto precisa ser low poly, MAAAAAS, se puder, provavelmente será! Haha’": "My main bowl, for example, was born that way, built entirely in low poly. Not every project has to be low poly, BUUUUT, if it can be, it probably will be! Haha",
"Monocromático": "Monochrome",
"Mostrar senha": "Show password",
"Mármore": "Marble",
"Naquela mesma madrugada, comprei minha primeira impressora 3D.": "That same night, I bought my first 3D printer.",
"Naquele momento percebi que, de certa forma, eu também já havia lançado o meu dado.": "Right then I realized that, in a way, I had thrown my die too.",
"Nas versões Ovatum e Longum, a mesma linguagem ganha proporções distintas, permitindo composições individuais ou em conjunto sem perder sua identidade.": "In the Ovatum and Longum versions, the same language takes on different proportions, so they work on their own or together without losing their identity.",
"No fim, tudo se conecta.": "In the end, it all connects.",
"Nodus Organizer": "Nodus Organizer",
"Nome completo, CPF, telefone e endereço de entrega vão para a ālea & Co. pelo WhatsApp, para emitir a nota fiscal e entregar a peça; ficam guardados pelo prazo das obrigações fiscais.": "Full name, CPF (Brazilian tax ID), phone and delivery address go to ālea & Co. over WhatsApp, to issue the invoice and deliver the piece; they’re kept for as long as tax obligations require.",
"Nome do pet": "Pet name",
"Nome do pet em baixo ou alto relevo na cor do objeto, dependendo da geometria da peça.": "Pet name engraved or embossed in the color of the piece, depending on the piece’s geometry.",
"Nossa linha PET foi criada para trazer mais alegria e personalidade à sua casa, criando um cantinho especial para quem, mesmo sem dizer uma palavra, transborda amor, alegria e companheirismo.": "Our PET line was made to bring more joy and personality to your home, creating a special little corner for the ones who, without saying a word, overflow with love, joy and companionship.",
"O Cerrado.": "The Cerrado.",
"O Vase Prismatic é formado por uma sequência de faces marcadas e volumes geométricos que criam diferentes reflexos ao longo de toda a sua superfície. O resultado é um desenho contemporâneo, cheio de movimento, que ganha novas formas conforme o ângulo de quem observa e a incidência da luz.": "The Vase Prismatic is made of a sequence of sharp faces and geometric volumes that create different reflections all over its surface. The result is a contemporary design, full of movement, that takes on new shapes depending on where you look from and how the light hits it.",
"O acaso no nome. O cuidado em tudo o que faço!": "Chance in the name. Care in everything I do!",
"O acaso.": "Chance.",
"O comedouro da Ayla veio de mais um sentimento de justiça. Eu já tinha criado um pra cada um dos meus filhos, e ainda faltava a minha irmã caçula, a filha preferida da minha mãe! Haha’": "Ayla’s bowl came from yet another sense of fairness. I’d already made one for each of my kids, and my little sister was still missing — my mom’s favorite daughter! Haha",
"O dado lançado.": "The die is cast.",
"O nome não é adesivo colado. Ele é impresso junto com a peça, em baixo relevo na cor do objeto, então não descasca, não desbota e não sai na lavagem. A tigela interna é de inox e sai pra lavar.": "The name isn’t a sticker. It’s printed together with the piece, engraved in the color of the object, so it doesn’t peel, doesn’t fade and doesn’t wash off. The inner bowl is stainless steel and comes out for washing.",
"O que não dá para trocar": "What can’t be exchanged",
"O resumo honesto": "The honest summary",
"O risco.": "The risk.",
"O valor do kit sai por WhatsApp, junto com as opções de estampa.": "The kit price comes over WhatsApp, along with the pattern options.",
"O ālea Pet Bowl Wave foi criado pensando em dar mais cor a um comedouro elevado. O do Matteo a gente quis texturizado e com poucas cores. Já o Wave tem essas ondas na base e foi pensado desde o início pra três cores.": "The ālea Pet Bowl Wave was designed to bring more color to a raised bowl. Matteo’s we wanted textured and with few colors. The Wave has these waves at the base and was designed for three colors from the start.",
"Onde cada impressão começa com um sonho!": "Where every print starts with a dream!",
"Opção 1": "Option 1",
"Opção 1 11,1 × 15,6 × 15,6 cm · Opção 2 11,1 × 10,6 × 10,6 cm · Opção 3 10,0 × 17,9 × 17,9 cm (altura × largura × comprimento, montado)": "Option 1 11.1 × 15.6 × 15.6 cm · Option 2 11.1 × 10.6 × 10.6 cm · Option 3 10.0 × 17.9 × 17.9 cm (height × width × length, assembled)",
"Opção 2": "Option 2",
"Opção 3": "Option 3",
"Orbis": "Orbis",
"Orbis Mini 8,4 × 9,1 × 9,1 cm · Orbis Pequeno 12,5 × 13,4 × 13,4 cm · Quadrum Pequeno 12,5 × 13,4 × 13,4 cm · Quadrum Grande 12,5 × 13,4 × 23,1 cm (altura × largura × comprimento, com os pés)": "Orbis Mini 8.4 × 9.1 × 9.1 cm · Orbis Small 12.5 × 13.4 × 13.4 cm · Quadrum Small 12.5 × 13.4 × 13.4 cm · Quadrum Large 12.5 × 13.4 × 23.1 cm (height × width × length, with the feet)",
"Orçamentos e personalizados": "Quotes and custom orders",
"Orçamentos e personalizados, clique aqui!": "Quotes and custom orders, click here!",
"Os seus direitos — e onde exercer sozinho": "Your rights — and where to use them yourself",
"Os triângulos.": "The triangles.",
"Ovatum": "Ovatum",
"Ovatum 15,5 × 10,5 × 10,5 cm · Longum 20,0 × 9,9 × 9,9 cm (altura × largura × comprimento)": "Ovatum 15.5 × 10.5 × 10.5 cm · Longum 20.0 × 9.9 × 9.9 cm (height × width × length)",
"PLA é um material utilizado na impressão 3D, produzido a partir de fontes renováveis, como milho e cana-de-açúcar. É leve, versátil e proporciona excelente acabamento.": "PLA is a 3D printing material made from renewable sources like corn and sugarcane. It’s light, versatile and gives an excellent finish.",
"PRODUTOS PERSONALIZADOS": "PERSONALIZED PRODUCTS",
"Passeio · PET": "Walk · PET",
"Pen Holder": "Pen Holder",
"Perolizado": "Pearl",
"Personalização": "Personalization",
"Personalize agora": "Personalize now",
"Personalize sua peça": "Personalize your piece",
"Pet Bowl": "Pet Bowl",
"Pet Bowl + Poop Bag Holder – Watermelon Edition": "Pet Bowl + Poop Bag Holder – Watermelon Edition",
"Pet Bowl Wave": "Pet Bowl Wave",
"Peça com defeito": "Defective piece",
"Poop Bag Holder": "Poop Bag Holder",
"Por favor, aceite os termos da declaração.": "Please accept the terms of the statement.",
"Por favor, digite o nome do pet.": "Please type your pet’s name.",
"Por favor, escolha o acabamento da cor do topo.": "Please choose the finish for the top color.",
"Por favor, escolha o formato.": "Please choose the shape.",
"Por favor, escolha o tamanho.": "Please choose the size.",
"Por favor, selecione a cor da peça.": "Please select the color of the piece.",
"Por isso, esse comedouro é uma edição especial, feita exclusivamente para ela.": "That’s why this bowl is a special edition, made just for her.",
"Por isso, ālea.": "That’s why: ālea.",
"Por serem feitos sob encomenda e personalizados conforme suas escolhas, os pedidos não poderão ser cancelados ou devolvidos após a confirmação do pagamento caso a produção já tenha começado, exceto em casos de defeito, vício ou erro de fabricação.": "Because they’re made to order and personalized to your choices, orders can’t be canceled or returned after payment is confirmed if production has already started, except in cases of defect, flaw or manufacturing error.",
"Prata": "Silver",
"Prazo de produção": "Production time",
"Prazo de produção, entrega, direito de arrependimento e política de troca das peças personalizadas da ālea & Co.": "Production time, shipping, right of withdrawal and exchange policy for ālea & Co.’s personalized pieces.",
"Preto": "Black",
"Preto com Azul": "Black & Blue",
"Principal": "Main",
"Produtos": "Products",
"Produzida em impressão 3D, é uma peça funcional que também faz parte da decoração — porque até os pequenos detalhes merecem ser especiais.": "3D printed, it’s a functional piece that’s also part of the decor — because even the little details deserve to be special.",
"Produção": "Production",
"Pronto": "Done",
"Prévia: a conta e os dados ficam só neste aparelho. Nada vai pro servidor.": "Preview: the account and data stay only on this device. Nothing goes to the server.",
"Próxima foto": "Next photo",
"Próximo": "Next",
"Pular para o conteúdo": "Skip to content",
"Pular para o menu de categorias": "Skip to the category menu",
"Quadrum": "Quadrum",
"Qualquer dúvida, nas fotos em tela cheia, você encontra os nomes e as tonalidades reais de cada cor.": "Any questions? In the full-screen photos you’ll find the names and the real shades of each color.",
"Quando falo minha, é porque sempre tive um sonho de ter uma marca de roupa, e não está muito distante, ainda vou realizar! E vai ter a minha capivara também!": "When I say mine, it’s because I’ve always dreamed of having a clothing brand — and it’s not that far off, I’m still gonna make it happen! And it’ll have my capybara too!",
"Que dados o site da ālea & Co. coleta, para quê, e como pedir a exclusão deles.": "What data the ālea & Co. site collects, what for, and how to ask for it to be deleted.",
"Quem responde por isto": "Who answers for this",
"Quem é a ālea & Co.": "Who ālea & Co. is",
"Quem é o responsável": "Who’s responsible",
"Receber código por e-mail": "Get a code by email",
"Rosa Claro": "Light Pink",
"Roxo": "Purple",
"Sacola": "Bag",
"Sacola de Compras": "Shopping Bag",
"Sacola de Compras e Finalizar Compra da ālea & Co.": "ālea & Co. Shopping Bag and Checkout",
"Sacola vazia": "Empty bag",
"Se a ālea & Co. começou por impulso, tudo o que veio depois passou longe de ser feito por impulso.": "If ālea & Co. started on impulse, everything that came after was anything but impulsive.",
"Se o Luke tinha ganhado o dele, o Matteo também tinha que ganhar. Só que não podia ser igual, tinha que ser diferente.": "If Luke got his, Matteo had to get one too. But it couldn’t be the same — it had to be different.",
"Segurança": "Security",
"Sem nome": "No name",
"Sempre fui apaixonado por esse estilo.": "I’ve always been crazy about this style.",
"Senha": "Password",
"Seu desenho arredondado cria um efeito delicado de luz e sombra, valorizando cada detalhe e fazendo com que a peça se destaque mesmo nas composições mais simples.": "Its rounded design creates a delicate play of light and shadow, highlighting every detail and making the piece stand out even in the simplest setups.",
"Seu desenho elevado ajuda a manter o sabonete apoiado sem perder a leveza visual da peça, enquanto as curvas criam um acabamento moderno e diferente em todos os ângulos.": "Its raised design keeps the soap propped up without losing the piece’s visual lightness, while the curves give it a modern finish that looks different from every angle.",
"Seu desenho equilibra precisão e leveza: uma estrutura marcada por ritmo e continuidade, onde luz e sombra passam a fazer parte da própria forma.": "Its design balances precision and lightness: a structure marked by rhythm and continuity, where light and shadow become part of the form itself.",
"Simulação. A cor na tela pode variar um pouco da peça real.": "Simulation. The color on screen may vary a bit from the real piece.",
"Soap Dish": "Soap Dish",
"Sob encomenda, 3 dias úteis após a confirmação de pagamento!": "Made to order, 3 business days after payment is confirmed!",
"Sou exigente com detalhes, acabamento, materiais e entrega. Escolho cuidadosamente os filamentos, reviso cada personalização e detalhe, e quando alguma coisa não fica como deveria, eu surto!": "I’m picky about details, finish, materials and delivery. I carefully choose the filaments, check every personalization and detail, and when something doesn’t turn out the way it should, I freak out!",
"Stria Planter": "Stria Planter",
"Sua lista está vazia. Toque no coração na página de uma peça para guardá-la aqui.": "Your list is empty. Tap the heart on a piece’s page to save it here.",
"Sua sacola está vazia.": "Your bag is empty.",
"Subcategorias de HOME": "HOME subcategories",
"Subtotal": "Subtotal",
"Sugestões": "Suggestions",
"Só que foram muitos desafios. Eu não sabia modelar, muito menos fazer low poly. Pedi ajuda à minha cunhada, que é arquiteta, e depois de muito trabalho e testes, a gente chegou nessa peça, que eu achei incrível.": "But there were a lot of challenges. I didn’t know how to model, let alone do low poly. I asked my sister-in-law, who’s an architect, for help, and after a lot of work and testing, we landed on this piece, which I think is amazing.",
"Tamanho": "Size",
"Terracota": "Terracotta",
"Tinha que ser ālea. ❤️": "It had to be ālea. ❤️",
"Toque novamente para tela cheia.": "Tap again for full screen.",
"Total": "Total",
"Transparente": "Clear",
"Tricolor": "Three-tone",
"Trocas, devolução e entrega": "Returns, exchanges & shipping",
"Tudo trafega criptografado (https). Não existe senha nossa pra vazar. O acesso aos dados é só de quem opera o pedido. Se acontecer um incidente com risco pra você, a ālea & Co. avisa você e a ANPD no prazo do regulamento (Resolução CD/ANPD nº 15/2024).": "Everything travels encrypted (https). There’s no password of ours to leak. Only the people handling the order can access the data. If an incident puts you at risk, ālea & Co. will notify you and the ANPD (Brazil’s data protection authority) within the regulatory deadline (Resolution CD/ANPD No. 15/2024).",
"Um acaso que virou escolha.": "A chance that became a choice.",
"Um objeto de presença sutil, pensado para integrar o ambiente sem apenas ocupá-lo.": "An object with a subtle presence, designed to blend into the space rather than just take it up.",
"Uma peça criada para levar textura, forma e um toque de design para pequenos cantos da casa — daqueles detalhes que chamam atenção sem precisar disputar espaço com o restante da decoração.": "A piece made to bring texture, shape and a touch of design to the little corners of your home — one of those details that catches the eye without fighting for space with the rest of the decor.",
"Uma peça versátil, delicada e cheia de presença — feita para transformar pequenos espaços em cantinhos especiais.": "A versatile, delicate piece full of presence — made to turn small spaces into special little corners.",
"Vase Prismatic": "Vase Prismatic",
"Ver todas as peças de HOME": "See all HOME pieces",
"Ver todas as peças de PET": "See all PET pieces",
"Verde": "Green",
"Verde Limão": "Lime Green",
"Verde Menta": "Mint Green",
"Verde Oliva": "Olive Green",
"Vermelho": "Red",
"Você adicionou esta criação à sua sacola de compras.": "You added this piece to your shopping bag.",
"a informar": "to be confirmed",
"cada suporte 2,9 × 2,4 × 6,3 cm (altura × largura × comprimento; são 2 peças)": "each holder 2.9 × 2.4 × 6.3 cm (height × width × length; 2 pieces)",
"cassianorosado@alea3d.co": "cassianorosado@alea3d.co",
"eai, bora? — o canal do Cassiano no Instagram": "eai, bora? — Cassiano’s channel on Instagram",
"foto em breve": "photo coming soon",
"no computador, sobre quais peças o mouse parou;": "on a computer, which pieces your mouse hovered over;",
"ver produto →": "see product →",
"Álbum de fotos": "Photo album",
"Álbuns por configuração": "Albums by configuration",
"É brasileira, está presente no Cerrado e faz parte de Goiás, minha terra natal! É um animal tranquilo, “amoroso” e dócil. Para mim, ela representa carinho, convivência e amor — e também um pouco de quem eu sou e do que quero que a ālea & Co. transmita.": "She’s Brazilian, lives in the Cerrado and is part of Goiás, my home state! She’s a chill, “loving” and gentle animal. To me, she stands for affection, getting along and love — and also a bit of who I am and what I want ālea & Co. to get across.",
"É como as fotos do Instagram foram feitas: as duas peças na mesma estampa, personalizadas com o mesmo nome, embaladas juntas com a tag da marca.": "That’s how the Instagram photos were made: both pieces in the same pattern, personalized with the same name, packed together with the brand tag.",
"Última atualização: 14/09/2026": "Last updated: 09/14/2026",
"Última atualização: 23/09/2026 · Lei 13.709/2018 (LGPD)": "Last updated: 09/23/2026 · Law 13.709/2018 (LGPD)",
"— Todos os direitos reservados.": "— All rights reserved.",
"← categorias": "← categories",
"← voltar para a página inicial": "← back to the home page",
"← voltar para o feed": "← back to the feed",
"Rosa": "Pink",
"Cassiano Rosado": "Cassiano Rosado",
"Jataí": "Jataí",
"GO": "GO",
"Mirella Gaetti": "Mirella Gaetti",
"@aylapompom": "@aylapompom",
"Pode": "Sure",
"Cadastre-se": "Sign up",
"Não tem uma conta?": "Don’t have an account?",
"ou": "or",
"Como funciona": "How it works",
"Ao entrar você concorda com a": "By signing in you agree to the",
"Política de Privacidade": "Privacy Policy",
"Política de privacidade": "Privacy policy",
"Quem somos nós": "About us",
"Trocas, devoluções e entregas": "Returns, exchanges & shipping",
"· CNPJ": "· CNPJ",
"· identidade visual por": "· visual identity by",
"da ālea & Co.": "from ālea & Co.",
"Posso lembrar as peças que você viu, pra te mostrar de novo quando voltar?": "Can I remember the pieces you checked out, so I can show them to you again when you’re back?",
"em breve": "coming soon",
"Em breve": "Coming soon",
"Sob consulta": "Price on request",
"a partir de": "from",
"Conta": "Account",
"Continuar com o Google": "Continue with Google",
"Mensagem para Presente": "Gift Message",
"Adicione uma mensagem personalizada que será impressa e enviada com seu presente.": "Add a personal message — we’ll print it and send it along with your gift.",
"Voltar ao site": "Back to the site",
"Ver as peças": "See the pieces",
"(exemplo)": "(example)",
"Idioma": "Language",
"Continuar": "Continue",
"Por quanto tempo": "For how long",
"Branco Perolizado": "Pearl White",
"G": "L",
"P": "S",
"GG": "XL",
"M": "M",
"×": "×",
"ou <a href=\"finalizar-compra.html#/compra\" class=\"loja-link sublinha\">continuar sem cadastro</a>": "or <a href=\"finalizar-compra.html#/compra\" class=\"loja-link sublinha\">continue without an account</a>",
"continuar sem cadastro": "continue without an account",
"A verificação de segurança demorou demais. Tente de novo.": "The security check took too long. Please try again.",
"A verificação de segurança expirou. Tente de novo.": "The security check expired. Please try again.",
"A verificação de segurança falhou. Tente de novo.": "The security check failed. Please try again.",
"As duas senhas não são iguais.": "The two passwords don’t match.",
"Autenticação": "Authentication",
"CEP não encontrado": "ZIP code (CEP) not found",
"CPF inválido": "Invalid CPF (Brazilian tax ID)",
"Cartão de crédito": "Credit card",
"Conta de prévia excluída deste aparelho.": "Preview account deleted from this device.",
"Destinatário:": "Recipient:",
"Digite sua senha.": "Enter your password.",
"Digite um e-mail válido": "Enter a valid email",
"Digite um e-mail válido.": "Enter a valid email.",
"Endereços": "Addresses",
"Enquanto o pagamento pelo site não liga, o pedido completo segue pelo WhatsApp da ālea & Co.": "Until online payment goes live, your full order goes through ālea & Co.’s WhatsApp.",
"Entrega para": "Ship to",
"Esse é o máximo que cabe na peça.": "That’s the most that fits on the piece.",
"Excluir sua conta da ālea & Co.? Seus dados de cadastro e a memória da sua visita serão apagados.": "Delete your ālea & Co. account? Your profile data and your visit history will be erased.",
"Filamentos desta foto, de cima para baixo": "Filaments in this photo, top to bottom",
"Frete: a combinar pelo CEP.": "Shipping: arranged by ZIP code (CEP).",
"Indo para o pagamento…": "Heading to payment…",
"Isso ainda não está ligado no servidor.": "This isn’t live on the server yet.",
"Marque a opção acima para personalizar.": "Tick the option above to personalize.",
"Minha Conta": "My Account",
"Na sua Lista de Desejos": "In your Wishlist",
"Não achamos esse CEP. Confira os números.": "We couldn’t find that ZIP code (CEP). Check the numbers.",
"Não deu certo agora. Tente de novo.": "That didn’t work. Please try again.",
"Não deu pra carregar a verificação de segurança. Confira a internet e tente de novo.": "Couldn’t load the security check. Check your connection and try again.",
"O código expirou. Peça um novo.": "The code expired. Ask for a new one.",
"O código tem 6 números.": "The code has 6 digits.",
"O pagamento não respondeu agora. Nada foi cobrado. Tente de novo em instantes.": "Payment didn’t respond. You weren’t charged. Try again in a moment.",
"O servidor da conta não respondeu. Tente de novo em instantes.": "The account server didn’t respond. Try again in a moment.",
"O valor pago agora é o das peças. O frete é combinado com a ālea & Co. pelo WhatsApp, depois do pagamento.": "What you pay now is for the pieces. Shipping is arranged with ālea & Co. over WhatsApp, after payment.",
"Orçamento de peça personalizada": "Quote for a custom piece",
"Pagamento escolhido:": "Payment method:",
"Pedidos já feitos ficam só pelo tempo que a lei fiscal exige.": "Past orders are kept only as long as tax law requires.",
"Por favor, escolha a cor do nome.": "Please choose the name color.",
"Por favor, escolha o acabamento da cor do nome.": "Please choose the finish for the name color.",
"Por favor, volte e coloque o nome do seu pet.": "Please go back and add your pet’s name.",
"Preencha o nome": "Fill in the name",
"Preencha o número (ou S/N)": "Fill in the number (or S/N if none)",
"Remover item da sacola": "Remove item from bag",
"Sua conta": "Your account",
"Sua sessão terminou. Entre de novo.": "Your session ended. Please sign in again.",
"Telefone com DDD": "Phone with area code",
"Tem certeza de que deseja remover este item da sua sacola?": "Are you sure you want to remove this item from your bag?",
"Tigela interna em inox, removível pra lavar": "Stainless steel inner bowl, removable for washing",
"Toque na peça que você quer pintar.": "Tap the part you want to color.",
"Agora escolha a cor.": "Now pick the color.",
"Toque na peça para escolher a cor": "Tap the piece to choose the color",
"Total das peças:": "Pieces total:",
"Frete": "Shipping",
"sem juros": "interest-free",
"sem personalização": "no personalization",
"Nome: sem nome": "Name: no name",
"cor do nome:": "name color:",
"cores da peça:": "piece colors:",
"peça": "piece",
"peças": "pieces",
"cão": "dog",
"médio": "medium",
"pequeno": "small",
"grande": "large",
"(cores a combinar depois do pagamento)": "(colors to be arranged after payment)",
"(fora os itens sob consulta)": "(not counting price-on-request items)",
"quatro cores": "four colors",
"três cores": "three colors",
"duas cores": "two colors",
"uma cor": "one color",
"WhatsApp ainda não configurado": "WhatsApp not set up yet",
"Oi! Vim pelo site da ālea & Co. e quero um orçamento de uma peça personalizada.": "Hi! I came from the ālea & Co. site and I’d like a quote for a custom piece.",
"Multfila · PLA · Mult Matte · Bordô (4225-PCI-PLM-118)": "Multfila · PLA · Mult Matte · Burgundy (4225-PCI-PLM-118)",
"Sair": "Sign out",
"Salvar": "Save",
"Editar": "Edit",
"Excluir": "Delete",
"Pedidos": "Orders",
"Meus pedidos": "My orders",
"Dados pessoais": "Personal info",
"Meus pets": "My pets",
"Nome completo": "Full name",
"Data de aniversário": "Birthday",
"Endereço": "Address",
"Número": "Number",
"Complemento": "Apt, suite, etc.",
"Bairro": "Neighborhood",
"Cidade": "City",
"Estado": "State",
"CEP": "ZIP code (CEP)",
"Finalizar compra": "Checkout",
"Forma de pagamento": "Payment method",
"Pix": "Pix",
"Boleto": "Bank slip (boleto)",
"Resumo do pedido": "Order summary",
"Mensagem para presente": "Gift message",
"O ālea Urubu Mascote Flamengo nasce para quem carrega o time no peito e quer ter essa paixão à vista, na estante, na mesa de trabalho ou no cantinho da coleção.": "The ālea Urubu Mascote Flamengo is made for anyone who wears the club on their chest and wants that passion on display — on the shelf, on the desk or in their collection corner.",
"Cheio de detalhes, das cores da camisa à postura de quem entra em campo, ele é produzido peça por peça em PLA, com acabamento Clássico ou Perolizado no vermelho, que ganha brilho e profundidade com a luz.": "Packed with detail, from the jersey colors to the stance of a player walking onto the pitch, it’s made piece by piece in PLA, with a Classic or Pearl finish on the red that picks up shine and depth in the light.",
"Disponível em três tamanhos: Pequeno, Médio e Gigante. E com um toque só seu: o nome que você escolher vai nas costas, acima do número da camisa.": "Available in three sizes: Small, Medium and Giant. And with a touch that’s all yours: the name you pick goes on the back, above the shirt number.",
"Mais do que um boneco, é a torcida em forma de peça.": "More than a figure, it’s the whole crowd in one piece.",
"O nome que você escolher, nas costas, acima do número da camisa, sem custo.": "The name you pick, on the back, above the shirt number, at no extra cost.",
"Pequeno 25,8 × 21,2 × 7,8 cm · Médio 46,5 × 38,1 × 13,9 cm · Gigante 59,4 × 48,7 × 17,8 cm (altura × largura × profundidade)": "Small 25.8 × 21.2 × 7.8 cm · Medium 46.5 × 38.1 × 13.9 cm · Giant 59.4 × 48.7 × 17.8 cm (height × width × depth)",
"Nome nas costas": "Name on the back",
"Filamento": "Filament",
"Filamento: Clássico": "Filament: Classic",
"Filamento: Perolizado": "Filament: Pearl",
"Por favor, digite o nome.": "Please type the name.",
"Por favor, escolha o filamento.": "Please choose the filament.",
"Pequeno": "Small",
"Médio": "Medium",
"Gigante": "Giant",
"Grande": "Large",
"Pequeno porte": "Small breeds",
"Médio e grande porte": "Medium & large breeds",
"Tamanho: Pequeno porte": "Size: Small breeds",
"Tamanho: Médio e grande porte": "Size: Medium & large breeds",
"Pequeno porte 15,7 × 15,9 × 15,9 cm · Médio e grande porte 18,0 × 18,2 × 18,2 cm (altura × largura × comprimento)": "Small breeds 15.7 × 15.9 × 15.9 cm · Medium & large breeds 18.0 × 18.2 × 18.2 cm (height × width × length)",
"Pequeno porte 13,3 × 16,6 × 16,2 cm · Médio e grande porte 15,0 × 18,8 × 18,4 cm (altura × largura × comprimento)": "Small breeds 13.3 × 16.6 × 16.2 cm · Medium & large breeds 15.0 × 18.8 × 18.4 cm (height × width × length)",
"ālea Pet Bowl Caesar": "ālea Pet Bowl Caesar",
"ālea Pet Bowl Prisma": "ālea Pet Bowl Prisma",
"Inspirado na beleza das pedras preciosas e na precisão de suas lapidações, o ālea Pet Bowl Prisma transforma formas geométricas em uma peça de personalidade única.": "Inspired by the beauty of precious stones and the precision of their cuts, the ālea Pet Bowl Prisma turns geometric shapes into a piece with a unique personality.",
"Suas facetas cuidadosamente desenhadas criam um jogo de luz e sombra que valoriza cada ângulo, enquanto sua silhueta escultural equilibra elegância, modernidade e funcionalidade.": "Its carefully designed facets create a play of light and shadow that enhances every angle, while its sculptural silhouette balances elegance, modernity and functionality.",
"Sua estrutura elevada proporciona uma posição mais confortável durante a alimentação, unindo praticidade e bem-estar a um design que valoriza cada detalhe.": "Its raised structure provides a more comfortable position while eating, combining practicality and well-being with a design that values every detail.",
"Mais do que um comedouro, o Prisma é um elemento de design que integra o universo pet à decoração, trazendo sofisticação e originalidade aos espaços compartilhados com nossos filhos de quatro patas!": "More than a feeder, the Prisma is a design element that brings the pet world into the décor, adding sophistication and originality to the spaces shared with our four-legged children!",
"A natureza não busca a perfeição das formas. É justamente em suas irregularidades que revela sua beleza mais autêntica.": "Nature does not seek perfection of form. It is precisely in its irregularities that it reveals its most authentic beauty.",
"Inspirado na essência das rochas e na maneira como o tempo esculpe a matéria, o ālea Pet Petra nasce do encontro entre a força da natureza e a delicadeza do nosso design low poly, uma das expressões mais marcantes da identidade da ālea & Co.": "Inspired by the essence of rocks and the way time sculpts matter, the ālea Pet Petra is born from the meeting between the strength of nature and the delicacy of our low poly design, one of the most striking expressions of the ālea & Co. identity.",
"Suas formas geométricas reinterpretam a beleza das pedras sob um olhar contemporâneo, transformando a inspiração natural em uma criação autoral, onde cada ângulo revela personalidade, equilíbrio e originalidade.": "Its geometric shapes reinterpret the beauty of stones through a contemporary eye, turning natural inspiration into an authorial creation, where every angle reveals personality, balance and originality.",
"Criado para quem acredita que o cuidado com nossos companheiros também faz parte da maneira como escolhemos viver e decorar, o Petra leva ao universo pet uma estética singular, que traduz nossa paixão por transformar formas simples em peças extraordinárias.": "Created for those who believe that caring for our companions is also part of the way we choose to live and decorate, the Petra brings a singular aesthetic to the pet world, one that conveys our passion for turning simple forms into extraordinary pieces.",
"ālea Pet Petra": "ālea Pet Petra"
};

window.ALEA_EN_RE = [
  [/^Ampliar foto (\d+) de (.+)$/, "Zoom in on photo $1 of $2"],
  [/^Abrir o álbum (.+) \((\d+) fotos?\)$/, "Open the $1 album ($2 photos)"],
  [/^Kit ālea — foto (\d+)$/, "ālea Kit — photo $1"],
  [/^(ālea .+) — foto (\d+)$/, "$1 — photo $2"],
  [/^Sacola com 1 item$/, "Bag with 1 item"],
  [/^Sacola com (\d+) itens$/, "Bag with $1 items"],
  [/^Tirar (.+) da sacola$/, "Remove $1 from the bag"],
  [/^<small class="a-partir">a partir de<\/small> (R\$ [\d.,]+)$/, "<small class=\"a-partir\">from</small> $1"],
  [/^Personalize <small class="janela3d-passo">(\d+) de (\d+)<\/small>$/, "Personalize <small class=\"janela3d-passo\">$1 of $2</small>"],
  [/^Um detalhe que transforma \+ (R\$ [\d.,]+)<small class="detalhe-extra">Deixe o nome do seu pet ainda mais especial adicionando cores\.<\/small>$/, "A detail that changes everything + $1<small class=\"detalhe-extra\">Make your pet’s name even more special by adding colors.</small>"],
  [/^Um detalhe que transforma \+ (R\$ [\d.,]+)$/, "A detail that changes everything + $1"],
  [/^Deixe o nome do seu pet ainda mais especial adicionando cores\.$/, "Make your pet’s name even more special by adding colors."],
  [/^Nome: (.+)$/, "Name: $1"],
  [/^Cor da base: escolha a cor$/, "Base color: choose the color"],
  [/^Cor do topo: escolha a cor$/, "Top color: choose the color"],
  [/^Cor principal: escolha a cor$/, "Main color: choose the color"],
  [/^Ver todas as peças de (.+)$/, "See all $1 pieces"],
  [/^\+ (\d+) itens? sob consulta$/, "+ $1 price-on-request items"],
];

(function () {
  var D = window.ALEA_EN;
  function cor(c) { return D[c] || c; }
  var MED = [["altura × largura × comprimento, montado com a gaveta", "height × width × length, assembled with the drawer"], ["altura × largura × comprimento, as 3 camadas montadas, com o insert", "height × width × length, all 3 layers assembled, with the insert"], ["altura × largura × comprimento, montado", "height × width × length, assembled"], ["altura × largura × comprimento, com os pés", "height × width × length, with the feet"], ["altura × largura × comprimento", "height × width × length"]];
  function medidas(s) {
    var t = s.replace(/(\d),(\d)/g, '$1.$2');
    for (var i = 0; i < MED.length; i++) t = t.split(MED[i][0]).join(MED[i][1]);
    t = t.replace(/\bOpção (\d)/g, 'Option $1').replace(/\bPequeno\b/g, 'Small').replace(/\bGrande\b/g, 'Large')
         .replace(/cada suporte/g, 'each holder').replace(/são (\d) peças/g, '$1 pieces');
    return t;
  }
  window.ALEA_EN_RE.push(
    [/^Monocromático: (.+)$/, function (_, c) { return 'Monochrome: ' + cor(c); }],
    [/^(.+) - (\d+) · Em estoque$/, function (_, c, n) { return cor(c) + ' - ' + n + ' · In stock'; }],
    [/^(Cor (?:da base|do topo|principal|do nome)): (.+)$/, function (_, k, c) { return cor(k) + ': ' + cor(c); }],
    [/^(Formato|Tamanho|Acabamento): (.+)$/, function (_, k, c) { return cor(k) + ': ' + cor(c); }],
    [/^[\d,]+ × [\d,]+ × [\d,]+ cm \(.+\)( <small>\(exemplo\)<\/small>)?$/, function (s) { return medidas(s).replace('(exemplo)', '(example)'); }]
  );
})();


(function () {
  var D = window.ALEA_EN;
  var P = { 'a cor da base': 'the base color', 'a cor do topo': 'the top color', 'a cor principal': 'the main color',
            'a cor do nome': 'the name color', 'o tamanho': 'the size', 'o formato': 'the shape', 'o acabamento': 'the finish',
            ' da cor da base': ' for the base color', ' da cor do topo': ' for the top color', ' da cor principal': ' for the main color',
            ' da cor do nome': ' for the name color' };
  window.ALEA_EN_RE.unshift(
    [/^Por favor, escolha (a cor da base|a cor do topo|a cor principal|a cor do nome|o tamanho|o formato|o acabamento)( da cor (?:da base|do topo|principal|do nome))?\.$/,
      function (_, a, b) { return 'Please choose ' + P[a] + (b ? P[b] : '') + '.'; }],
    [/^(.+): escolha a cor$/, function (_, k) { return (D[k] || k) + ': choose the color'; }],
    /* o carrinho monta a linha com o rotulo ja traduzido na pagina + a cor em portugues: "Monochrome: Branco Perolizado" */
    [/^(Monochrome|Two-tone|Three-tone|Exterior|Interior|Base color|Top color|Main color|Name color): (.+)$/, function (_, k, c) { return D[c] ? k + ': ' + D[c] : null; }]
  );
})();
